before_install:
  - pip install codecov
language: python
rvm:
  - 2.2
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev # 3.5 development branch
  - nightly # currently points to 3.6-dev
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-package=syschangemon
after_success:
  - codecov
before_deploy:
  - gem install fpm
  - gem install package_cloud
  - sudo apt-get -y install rpm
deploy:
  skip_cleanup: true
  provider: script
  script: /bin/true
  on:
    python: 3.4
after_deploy:
  - make
  - package_cloud push mcree/syschangemon/debian/wheezy *.deb
  - package_cloud push mcree/syschangemon/el/6 *.rpm
