before_install:
  - pip install codecov
  - gem install fpm
  - gem install package_cloud
  - sudo apt-get -y install rpm
language: python
rvm:
  - 2.2
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-package=syschangemon
deploy:
  provider: script
  script: travis-build-package.sh
after_success:
  - codecov
  - make
